---

name: Daily Build (ARM)

on:
  push:
    branches:
      - master
      - github-update
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    name: Build (${{ matrix.configuration.name }})
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        configuration:
          - name: Pinebook Pro
            script: ./build-pinebookpro.sh

          - name: Raspberry Pi
            script: ./build-rpi.sh
      # Don't fail the whole workflow if one config fails
      fail-fast: false

    steps:
      - name: Clean
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 16000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo ${{ matrix.configuration.script }} "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}"
